### ISSUE TITLE
Root logging level

### ISSUE THREAD

**Issue by tcibinan** [Spirals-Team/jtravis#16]
Currently root logging level of the library is debug which may lead to bad consequences.

F.i. I try to use jtravis with my spring boot app and what happens is spring searches for logback.xml and changes my app logging level to debug according to jtravis's [logback.xml](https://github.com/Spirals-Team/jtravis/blob/master/src/main/resources/logback.xml).

I think it may be useful to add logging profiles, f.e. dev and prod.

**Comment by surli** [comment]
Hi @tcibinan 

thanks for the feedback. I'll change it for next release.

**Comment by surli** [comment]
Done in 7981f95c8c813645d11da618d53cd405443dd90c
